### ISSUE TITLE
model wrong

### ISSUE THREAD

**Issue by chijames** [llStringll/Poly-encoders#1]
check the paper again, your encoder.py is totally nonsense.

**Comment by chijames** [comment]
btw, if you are copying code from https://github.com/sfzhou5678/PolyEncoder, though it's wrong, you'd better provide the reference in readme.

**Comment by llStringll** [comment]
Hi, thanks for the concern, can you elaborate why do you say "encoder.py is totally nonsense",
I implemented only Poly-encoder from the paper, neither the Bi-encoder, nor the cross-encoder, and my code does what it claims to do, I have results in readme, and obviously you can also test it .
Thanks
